# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
[[[1,2,3], [2,2,3]], [34,4,2], [7,5,3]]

[[[1, 2, 3], [2, 2, 3]], [34, 4, 2], [7, 5, 3]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [10]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use ``linspace`` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distan

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [17]:
np.linspace?

Signature: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dtype : dtype, optional

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [31]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(2)

array([0.71176343, 0.52491427])

In [22]:
np.random.rand(5,5,5)

array([[[0.36584409, 0.3711658 , 0.01489378, 0.16597229, 0.31177547],
        [0.23099418, 0.03198314, 0.75648498, 0.98007506, 0.02200002],
        [0.30977892, 0.94257471, 0.17278372, 0.90294285, 0.64609324],
        [0.66061155, 0.22984438, 0.08000319, 0.50080666, 0.07271539],
        [0.7718933 , 0.5951977 , 0.21536444, 0.43865465, 0.13147516]],

       [[0.64518833, 0.12517545, 0.85736779, 0.77403459, 0.82137431],
        [0.40484982, 0.06275043, 0.26406997, 0.01291052, 0.35973673],
        [0.77308814, 0.17647851, 0.24755508, 0.50514596, 0.44710526],
        [0.09884832, 0.61264259, 0.21266867, 0.19533531, 0.67111398],
        [0.54540428, 0.1884414 , 0.43909025, 0.65345737, 0.3806613 ]],

       [[0.48408227, 0.21098604, 0.60187695, 0.93913559, 0.41094612],
        [0.20014675, 0.8827149 , 0.0120331 , 0.81963426, 0.16674874],
        [0.95517646, 0.38669507, 0.54541345, 0.49791161, 0.75923727],
        [0.3579432 , 0.79292781, 0.9764697 , 0.63278301, 0.78774093],
        [0.73100

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [48]:
np.random.randn(2)

array([-0.27954018,  0.90078368])

In [45]:
np.random.randn(5,5)

array([[ 0.70154515,  0.22441999,  1.33563186,  0.82872577, -0.28247509],
       [ 0.64489788,  0.61815094, -0.81693168, -0.30102424, -0.29030574],
       [ 0.8695976 ,  0.413755  ,  2.20047208,  0.17955692, -0.82159344],
       [ 0.59264235,  1.29869894, -1.18870241,  0.11590888, -0.09181687],
       [-0.96924265, -1.62888685, -2.05787102, -0.29705576,  0.68915542]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100)

73

In [24]:
np.random.randint(1,100,10)

array([12, 65,  9,  9, 36, 54, 82, 58, 97, 53])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [31]:
arr = np.arange(24)
ranarr = np.random.randint(0,50,10)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
ranarr

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

## Reshape
Returns an array containing the same data with a new shape.

In [35]:
arr.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [36]:
ranarr

array([11,  2,  9, 39, 10, 19, 31,  7,  5, 20])

In [61]:
ranarr.max()

49

In [62]:
ranarr.argmax()

4

In [63]:
ranarr.min()

2

In [60]:
ranarr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [65]:
# Vector
arr.shape

(25,)

In [66]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
arr.reshape(1,25).shape

(1, 25)

In [70]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [41]:
var = 'Dheerendra'

In [39]:
var = '2'

In [40]:
type(var)

str

In [75]:
arr.dtype

dtype('int64')

# Great Job!